#' Cashflow plot for Monte Carlo simulation results
#' 
#' Creates a cashflow plot of the returned list of related outputs from the \code{\link[mcSimulation]{mcSimulation}} function using \code{\link{ggplot2}}
#' 
#' @param mcSimulation_object is a data frame of Monte Carlo simulations of cashflow outputs (in wide format, see example). Usually the "mcSimulation_object.csv" file generated by \code{\link[mcSimulation]{mcSimulation}} function.
#' @param cashflow_var_name is a character string representing the variable name used to define cashflow in the returned list of outputs from the \code{\link[mcSimulation]{mcSimulation}} function.
#' @param xlabel is a character string representing the title of the timeline of the intervention to be printed on the x axis in quotes.
#' @param ylabel is a character string representing the title of the units of the cashflow to be printed on the y axis.
#' @param color_25_75 is a character string referring to the color name for the shade fill of the 25-75\% quantile from the grDevices colors. The default is "grey40". 
#' @param color_5_95 is a character string referring to the shade fill of the 5-95\% quantile from the grDevices colors. The default is "grey70". 
#' @param color_median is a character string  referring to the color name for the median line from the grDevices colors. The default is  "blue".
#' 
#' @keywords Monte-Carlo decisionSupport decision-analysis cashflow risk uncertainty
#' 
#' @details 
#' This function automatically defines quantiles (5 to 95\% and 25 to 75\%) as well as a value for the median. 
#' 
#'  
#' @references 
#' Lanzanova Denis, Cory Whitney, Keith Shepherd, and Eike Luedeling. “Improving Development Efficiency through Decision Analysis: Reservoir Protection in Burkina Faso.” Environmental Modelling & Software 115 (May 1, 2019): 164–75. \url{https://doi.org/10.1016/j.envsoft.2019.01.016}.
#' 
#' @examples 
#' 
#' #Generate random dataset of 200 Monte Carlo simulations for cashflow
#' 
#' test_data <- data.frame(replicate(20, sample(-10000:10000, 200, rep = TRUE)))
#' 
#' #Make a name for the cashflow variables with time append (as is done in the mcSimulation function)
#' 
#' names(test_data) <-  gsub(x = names(test_data),
#'                           pattern = "X",
#'                           replacement = "cashflow")
#' 
#' 
#' plot_cashflow(mcSimulation_object = test_data, cashflow_var_name = "cashflow",
#'               xlabel = "Years with intervention",
#'               ylabel = "Annual cashflow in USD", 
#'               color_25_75 = "green4", color_5_95 = "green1",
#'               color_median = "red")
#'   
#' @importFrom magrittr %>%
#'   
#'@export plot_cashflow
#' 
plot_cashflow <- function(mcSimulation_object, cashflow_var_name, 
                          xlabel = "Timeline of intervention", 
                          ylabel = "Cashflow", 
                          color_25_75 = "grey40", 
                          color_5_95 = "grey70", 
                          color_median = "blue")
  {
  
  
  # Check if mcSimulation_object is class mcSimulation
  
  assertthat::assert_that(class(mcSimulation_object)[[1]] == "mcSimulation",
                          msg = "mcSimulation_object is not class 'mcSimulation', please provide a valid object. This does not appear to have been generated with 'mcSimulation' function.")
  
  
  # Create a dataframe from the mcSimulation_object
  
  data <- data.frame(mcSimulation_object$y,
                     mcSimulation_object$x)
  
  assertthat::assert_that(is.character(cashflow_var_name), msg = "cashflow_var_name is not a character string.")
  
  assertthat::assert_that(is.character(xlabel), msg = "xlabel is not a character string.")
  assertthat::assert_that(is.character(ylabel), msg = "ylabel is not a character string.")
  
  assertthat::assert_that(is.character(color_25_75), msg = "color_25_75 is not a character string.")
  assertthat::assert_that(is.character(color_5_95), msg = "color_5_95 is not a character string.")
  assertthat::assert_that(is.character(color_median), msg = "color_median is not a character string.")
  
  assertthat::assert_that(color_25_75 %in% grDevices::colors(), msg = "Please choose a color name for color_25_75 from the grDevices colors.")
  assertthat::assert_that(color_5_95 %in% grDevices::colors(), msg = "Please choose a color name for color_5_95 from the grDevices colors.")
  assertthat::assert_that(color_median %in% grDevices::colors(), msg = "Please choose a color name for color_median from the grDevices colors.")
  
  assertthat::assert_that(any(substr(names(data), 
                                     1, nchar(cashflow_var_name)) == cashflow_var_name), 
                          msg = "There are no variables that start with the same name as cashflow_var_name in your data.")
  
  ## Use 'complete.cases' from stats to remove NA
  if (any(is.na(data))) {
    warning(paste("Some data included \"NA\" and", 
                  table(is.na(data))[2], "rows were removed."))
    data <- data[stats::complete.cases(data), ]
  }
  
  #subset cashflow with cover 
  subset_data <- data %>%
    dplyr::select(dplyr::starts_with(cashflow_var_name)) %>%
    tidyr::pivot_longer(dplyr::starts_with(cashflow_var_name)) 
  
  subset_data <- subset_data %>%
    dplyr::mutate(x_scale = as.numeric(substr(subset_data$name, 
                                              nchar(cashflow_var_name) +1, 
                                              nchar(subset_data$name))))
  
  #define the quantiles of cashflow for each value of x_scale based on the replicates of the MC
  
  summary_subset_data <- subset_data %>%
    group_by(x_scale) %>%
    summarize(p5 = quantile(value, 0.05),
              p25 = quantile(value, 0.25),
              p50 = quantile(value, 0.50),
              p75 = quantile(value, 0.75),
              p95 = quantile(value, 0.95)) 
  
  ggplot(summary_subset_data, aes(x_scale)) +
    geom_ribbon(aes(ymin = p5, ymax = p95, fill="5 to 95")) +
    geom_ribbon(aes(ymin = p25, ymax = p75, fill="25 to 75")) +
    geom_line(aes(y = p50, color = "median")) +
    geom_line(aes(y = 0)) +
    scale_x_continuous(expand = c(0,0)) +
    scale_y_continuous(labels = scales::comma) +
    scale_fill_manual(values = c(color_25_75,  color_5_95)) +
    scale_color_manual(values = color_median) +
    guides(fill = guide_legend(reverse=T, order = 1)) +
    labs(x= xlabel, y= ylabel, fill="Quantiles (%)", color = "") +
    theme_bw() +
    theme(legend.margin = margin(-1, 0, 0, 0, unit = "cm"), 
          strip.background = element_blank())
  
  }


